### PR TITLE
Jim's changes on AM & RM specs for CS02

### PR DESCRIPTION
**Pull request by berezovskyi**
These 2 commits were extracted from @graybachelor's merge commit:

inklistrad_bild_2018-09-20__16_19

### CODE REVIEW

**Comment by jamsden** [comment]
These look right, they are the changes I already made for publishing the updated committee specifications. Nothing should have been changed after 51147780b7a17bbaf0b30023389573562d9292e5 on these files.

**Comment by berezovskyi** [comment]
I don't have push permissions yet so you have to merge it in, @jamsden

**Comment by berezovskyi** [comment]
would be best to rebase, btw

**Comment by berezovskyi** [comment]
@graybachelor for the future, don't push anything to master to avoid this kind of problem

**Pull request merged**
